In [2]:
#1. Data Collection

import pandas as pd
import numpy as np
import os 
from glob import glob

In [18]:
from glob import glob
files = glob('**/*.csv', recursive=True)
print(files)

[]

In [20]:
df = pd.read_csv(r'C:\Users\VRUSHTI\OneDrive\Documents\GitHub\Predictive-Space-Analytics\data\space_missions_dataset.csv')
print(df.head())

  Mission ID Mission Name Launch Date Target Type Target Name  Mission Type  \
0   MSN-0001    Mission-1  2025-01-01        Star       Titan  Colonization
1   MSN-0002    Mission-2  2025-01-08   Exoplanet  Betelgeuse  Colonization
2   MSN-0003    Mission-3  2025-01-15    Asteroid        Mars   Exploration
3   MSN-0004    Mission-4  2025-01-22   Exoplanet       Titan  Colonization
4   MSN-0005    Mission-5  2025-01-29   Exoplanet   Proxima b        Mining

   Distance from Earth (light-years)  Mission Duration (years)  \
0                               7.05                       5.2
1                              41.76                      23.0
2                              49.22                      28.8
3                              26.33                      17.8
4                               8.67                       9.2

   Mission Cost (billion USD)  Scientific Yield (points)  Crew Size  \
0                      526.68                       64.3         21
1                      234.08                       84.4         72
2                      218.68                       98.6         16
3                      232.89                       36.0         59
4                       72.14                       96.5         31

   Mission Success (%)  Fuel Consumption (tons)  Payload Weight (tons)  \
0                100.0                   731.88                  99.78
1                 89.6                  4197.41                  45.72
2                 98.6                  4908.00                  36.12
3                 90.0                  2569.05                  40.67
4                 73.2                   892.76                  12.40

  Launch Vehicle
0            SLS
1       Starship
2       Starship
3       Starship
4       Starship

In [21]:
print(df.shape)       # How many rows and columns?
print(df.columns)     # What are the column names?
df.head(10)           # Preview first 10 rows

(500, 15)
Index(['Mission ID', 'Mission Name', 'Launch Date', 'Target Type',
       'Target Name', 'Mission Type', 'Distance from Earth (light-years)',
       'Mission Duration (years)', 'Mission Cost (billion USD)',
       'Scientific Yield (points)', 'Crew Size', 'Mission Success (%)',
       'Fuel Consumption (tons)', 'Payload Weight (tons)', 'Launch Vehicle'],
      dtype='object')

,Mission ID,Mission Name,Launch Date,Target Type,Target Name,Mission Type,Distance from Earth (light-years),Mission Duration (years),Mission Cost (billion USD),Scientific Yield (points),Crew Size,Mission Success (%),Fuel Consumption (tons),Payload Weight (tons),Launch Vehicle
0,MSN-0001,Mission-1,2025-01-01,Star,Titan,Colonization,7.05,5.2,526.68,64.3,21,100.0,731.88,99.78,SLS
1,MSN-0002,Mission-2,2025-01-08,Exoplanet,Betelgeuse,Colonization,41.76,23.0,234.08,84.4,72,89.6,4197.41,45.72,Starship
2,MSN-0003,Mission-3,2025-01-15,Asteroid,Mars,Exploration,49.22,28.8,218.68,98.6,16,98.6,4908.00,36.12,Starship
3,MSN-0004,Mission-4,2025-01-22,Exoplanet,Titan,Colonization,26.33,17.8,232.89,36.0,59,90.0,2569.05,40.67,Starship
4,MSN-0005,Mission-5,2025-01-29,Exoplanet,Proxima b,Mining,8.67,9.2,72.14,96.5,31,73.2,892.76,12.40,Starship
5,MSN-0006,Mission-6,2025-02-05,Moon,Ceres,Colonization,13.69,8.8,452.42,45.1,42,100.0,1327.29,88.44,Ariane 6
6,MSN-0007,Mission-7,2025-02-12,Asteroid,Ceres,Research,1.02,5.0,220.38,44.7,74,95.5,211.20,42.07,SLS
7,MSN-0008,Mission-8,2025-02-19,Asteroid,Mars,Colonization,45.72,25.2,200.49,40.6,32,89.3,4600.53,39.34,SLS
8,MSN-0009,Mission-9,2025-02-26,Asteroid,Betelgeuse,Exploration,5.98,4.4,361.35,58.7,59,100.0,568.97,66.31,Ariane 6
9,MSN-0010,Mission-10,2025-03-05,Exoplanet,Betelgeuse,Colonization,28.87,18.9,265.98,23.9,34,99.3,2856.43,44.76,Starship

In [22]:
#2 Data Organization

files = glob('data/*.csv')
print(files)

[]

In [24]:
#3 Data Definition

print(df.dtypes)
print(df.info())

Mission ID                            object
Mission Name                          object
Launch Date                           object
Target Type                           object
Target Name                           object
Mission Type                          object
Distance from Earth (light-years)    float64
Mission Duration (years)             float64
Mission Cost (billion USD)           float64
Scientific Yield (points)            float64
Crew Size                              int64
Mission Success (%)                  float64
Fuel Consumption (tons)              float64
Payload Weight (tons)                float64
Launch Vehicle                        object
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 15 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Mission ID                         500 non-null    object
 1   Mission Name                       500 non-null    object
 2   Launch Date                        500 non-null    object
 3   Target Type                        500 non-null    object
 4   Target Name                        500 non-null    object
 5   Mission Type                       500 non-null    object
 6   Distance from Earth (light-years)  500 non-null    float64
 7   Mission Duration (years)           500 non-null    float64
 8   Mission Cost (billion USD)         500 non-null    float64
 9   Scientific Yield (points)          500 non-null    float64
 10  Crew Size                          500 non-null    int64
 11  Mission Success (%)                500 non-null    float64
 12  Fuel Consumption (tons)            500 non-null    float64
 13  Payload Weight (tons)              500 non-null    float64
 14  Launch Vehicle                     500 non-null    object
dtypes: float64(7), int64(1), object(7)
memory usage: 58.7+ KB
None

In [25]:
df.describe()                          # Numeric columns
df.describe(include='object')         # Categorical columns

,Mission ID,Mission Name,Launch Date,Target Type,Target Name,Mission Type,Launch Vehicle
count,500,500,500,500,500,500,500
unique,500,500,500,5,7,4,4
top,MSN-0001,Mission-1,2025-01-01,Star,Proxima b,Research,Starship
freq,1,1,1,112,81,132,140

In [31]:
# Unique value counts

for col in df.columns:
    print(f"{col}: {df[col].nunique()} unique values")
    print(df[col].value_counts(normalize=True).head(5))
    print("---")

Mission ID: 500 unique values
Mission ID
MSN-0001    0.002
MSN-0002    0.002
MSN-0003    0.002
MSN-0004    0.002
MSN-0005    0.002
Name: proportion, dtype: float64
---
Mission Name: 500 unique values
Mission Name
Mission-1    0.002
Mission-2    0.002
Mission-3    0.002
Mission-4    0.002
Mission-5    0.002
Name: proportion, dtype: float64
---
Launch Date: 500 unique values
Launch Date
2025-01-01    0.002
2025-01-08    0.002
2025-01-15    0.002
2025-01-22    0.002
2025-01-29    0.002
Name: proportion, dtype: float64
---
Target Type: 5 unique values
Target Type
Star         0.224
Planet       0.218
Moon         0.190
Exoplanet    0.186
Asteroid     0.182
Name: proportion, dtype: float64
---
Target Name: 7 unique values
Target Name
Proxima b    0.162
Mars         0.146
Io           0.144
Europa       0.140
Titan        0.140
Name: proportion, dtype: float64
---
Mission Type: 4 unique values
Mission Type
Research        0.264
Exploration     0.254
Colonization    0.250
Mining          0.232
Name: proportion, dtype: float64
---
Distance from Earth (light-years): 473 unique values
Distance from Earth (light-years)
4.67     0.004
6.93     0.004
49.38    0.004
13.06    0.004
24.08    0.004
Name: proportion, dtype: float64
---
Mission Duration (years): 231 unique values
Mission Duration (years)
26.6    0.014
26.1    0.012
19.0    0.012
8.9     0.012
25.8    0.012
Name: proportion, dtype: float64
---
Mission Cost (billion USD): 499 unique values
Mission Cost (billion USD)
405.66    0.004
265.98    0.002
327.76    0.002
38.80     0.002
436.87    0.002
Name: proportion, dtype: float64
---
Scientific Yield (points): 393 unique values
Scientific Yield (points)
98.3    0.010
52.9    0.008
15.6    0.006
95.6    0.006
35.4    0.006
Name: proportion, dtype: float64
---
Crew Size: 99 unique values
Crew Size
39    0.020
6     0.020
59    0.018
74    0.018
68    0.018
Name: proportion, dtype: float64
---
Mission Success (%): 184 unique values
Mission Success (%)
100.0    0.466
97.7     0.010
89.3     0.008
98.6     0.008
99.6     0.008
Name: proportion, dtype: float64
---
Fuel Consumption (tons): 500 unique values
Fuel Consumption (tons)
731.88     0.002
4197.41    0.002
4908.00    0.002
2569.05    0.002
892.76     0.002
Name: proportion, dtype: float64
---
Payload Weight (tons): 487 unique values
Payload Weight (tons)
64.91    0.004
65.23    0.004
39.92    0.004
63.51    0.004
6.90     0.004
Name: proportion, dtype: float64
---
Launch Vehicle: 4 unique values
Launch Vehicle
Starship        0.280
Ariane 6        0.248
Falcon Heavy    0.242
SLS             0.230
Name: proportion, dtype: float64
---

In [33]:
print(df['Mission Cost (billion USD)'].min(), df['Mission Cost (billion USD)'].max())   # Cost range
print(df['Launch Date'].min(), df['Launch Date'].max())        # Date range

13.32 538.32
2025-01-01 2034-07-26

In [34]:
#4 Data Cleaning

df.isnull().sum()
df.isnull().values.any()    # Quick True/False check

np.False_

In [36]:
# Option 1 - Fill with median (recommended)
df['Mission Cost (billion USD)'] = df['Mission Cost (billion USD)'].fillna(df['Mission Cost (billion USD)'].median())

# Option 2 - Use np.where to flag missing costs
df['cost_missing'] = np.where(df['Mission Cost (billion USD)'].isnull(), 1, 0)

In [37]:
print(df.duplicated().sum())
df = df.drop_duplicates()         # Remove duplicate rows

0

In [40]:
# Fix the Date Column
df['Launch Date'] = pd.to_datetime(df['Launch Date'], utc=True)
df['Year'] = df['Launch Date'].dt.year
df['Decade'] = (df['Year'] // 10) * 10

In [42]:
#Clean MissionStatus — Target Variable

print(df['MissionStatus'].value_counts())

# Simplify to binary: Success = 1, Failure = 0
df['MissionSuccess'] = np.where(
    df['MissionStatus'].str.contains('Success', case=False), 1, 0
)

KeyError: 'MissionStatus'